#!/bin/bash
wget 'https://www.archlinux.org/mirrorlist/?country=CN&protocol=http&protocol=https&ip_version=4' -O /etc/pacman.d/mirrorlist

sed -i -e 's/#Server/Server/g' /etc/pacman.d/mirrorlist

parted /dev/vda mklabel msdos mkpart primary ext4 1MiB 100%
pvcreate /dev/vda1
vgcreate arch dev/vda1
lvcreate -l 100%FREE arch -n root
mkfs.ext4 /dev/arch/root
mount /dev/arch/root /mnt
pacstrap /mnt base base-devel linux
genfstab -U /mnt >> /mnt/etc/fstab

# Commands executed on new system
arch-chroot /mnt ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
arch-chroot /mnt sed -i -e 's/#en_US.UTF-8/en_US.UTF-8/g' /etc/locale.gen
arch-chroot /mnt locale-gen
echo "LANG=en_US.UTF-8" > /mnt/etc/locale.conf
arch-chroot /mnt sed -i -e "s/block/block lvm2/g" /etc/mkinitcpio.conf
arch-chroot /mnt mkinitcpio -p linux
arch-chroot /mnt pacman --noconfirm -Syy
arch-chroot /mnt pacman --noconfirm -S grub openssh
arch-chroot /mnt sed -i -e 's/GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/g' /boot/grub/grub.cfg
arch-chroot /mnt grub-install --target=i386-pc /dev/vda
arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg
arch-chroot /mnt systemctl enable sshd dhcpcd
printf "\n"
echo -n "Please input the user name you wanna create: "
read MYUSER
arch-chroot /mnt useradd -m -G wheel -s /bin/bash $MYUSER
printf "Set root password\n"
arch-chroot /mnt passwd
echo "Set $MYUSER password"
arch-chroot /mnt passwd $MYUSER
umount /mnt
reboot

