#!/bin/bash
modprobe tcp_bbr
 echo "tcp_bbr" > /etc/modules-load.d/bbr.conf
 echo '
   net.core.default_qdisc=fq
   net.ipv4.tcp_congestion_control=bbr
 ' > /etc/sysctl.d/bbr.conf
 sysctl -p /etc/sysctl.d/bbr.conf
